"""Layer-neutral data contracts shared across the pipeline."""

from contracts.analysis import (
    ANALYSIS_POLICY_VERSION,
    LEGACY_PROVIDER_ID,
    AnalysisSpec,
    EventAnalysisCreate,
    EventAnalysisStatus,
    EventAnalysisView,
    StateChangeCreate,
    StateChangeView,
)
from contracts.collection import (
    CollectionRequest,
    FeedCollectionRequest,
    FeedPostItem,
    FeedPostKind,
    PostKind,
)
from contracts.enums import (
    AttentionLevel,
    ConsensusDirection,
    EventType,
    OpinionDirection,
    PositionStatus,
)
from contracts.intelligence import (
    AssetIntelligenceSnapshot,
    InvestorStateAggregationInput,
    InvestorStateContribution,
)
from contracts.opinion import (
    AssetOpinionExtraction,
    OpinionCreate,
    OpinionExtractionResult,
    OpinionProcessingResult,
    OpinionProcessingStatus,
    OpinionWriteResult,
    UnresolvedAsset,
    UnresolvedAssetHint,
)
from contracts.processing import (
    AnalysisProcessingError,
    CoreProcessingFailureCode,
    CoreProcessingResult,
    CoreProcessingWarning,
    ProcessingOutcome,
    ProcessingStage,
    ProcessRawEventCommand,
    RawEventNotFoundError,
)
from contracts.provider import (
    LLMApiStyle,
    LLMProviderConfig,
    LLMProviderError,
    ProviderCapabilities,
    ProviderErrorCode,
    StructuredOutputMode,
)
from contracts.raw_event import RawEventDTO, RawEventView, RawEventWriteResult
from contracts.state import (
    STATE_POLICY_VERSION,
    InvestorAssetStateSnapshot,
    OpinionTimelineEntry,
    StateReduction,
    StateTransitionType,
    StateUpdateResult,
)

__all__ = [
    "ANALYSIS_POLICY_VERSION",
    "AnalysisProcessingError",
    "AnalysisSpec",
    "AssetOpinionExtraction",
    "AssetIntelligenceSnapshot",
    "AttentionLevel",
    "CollectionRequest",
    "FeedCollectionRequest",
    "FeedPostItem",
    "FeedPostKind",
    "ConsensusDirection",
    "LLMApiStyle",
    "LLMProviderConfig",
    "LLMProviderError",
    "ProviderCapabilities",
    "ProviderErrorCode",
    "CoreProcessingFailureCode",
    "CoreProcessingResult",
    "CoreProcessingWarning",
    "EventAnalysisCreate",
    "EventAnalysisStatus",
    "EventAnalysisView",
    "EventType",
    "OpinionCreate",
    "OpinionDirection",
    "OpinionExtractionResult",
    "OpinionProcessingResult",
    "OpinionProcessingStatus",
    "OpinionTimelineEntry",
    "OpinionWriteResult",
    "PositionStatus",
    "PostKind",
    "InvestorStateAggregationInput",
    "InvestorStateContribution",
    "ProcessRawEventCommand",
    "ProcessingOutcome",
    "ProcessingStage",
    "RawEventDTO",
    "RawEventNotFoundError",
    "RawEventView",
    "RawEventWriteResult",
    "STATE_POLICY_VERSION",
    "StateChangeCreate",
    "StateChangeView",
    "StateReduction",
    "StateTransitionType",
    "StateUpdateResult",
    "InvestorAssetStateSnapshot",
    "LEGACY_PROVIDER_ID",
    "UnresolvedAsset",
    "UnresolvedAssetHint",
    "StructuredOutputMode",
]
